export const selectdata = {
	// 客户类型
	/* cus_type: [
		{value: "110",label: "其他自然人"},
		{value: "140",label: "小微企业主"},
		{value: "150",label: "个体工商户"}
	], */
	/* cus_typename: [
		{value: "110",label: "其他自然人"},
		{value: "140",label: "小微企业主"},
		{value: "150",label: "个体工商户"},
		{value: "270",label: "境外机构"},
		{value: "299",label: "其他组织机构"},
		{value: "130",label: "一般农户"},
		{value: "211",label: "企业"},
		{value: "221",label: "事业单位"},
		{value: "231",label: "社团团体"},
		{value: "241",label: "机关"},
		{value: "220",label: "个人经营户"},
	], */
	//证件类型
	cert_type: [
		{value: '10',label: "身份证"},
		{value: '12',label: "护照 "},
		{value: '13',label: "军官证"},
		{value: '14',label: "士兵证"},
		{value: '15',label: "港澳居民来往内地通行证 "},
		{value: '16',label: "台湾同胞来往内地通行证 "},
		{value: '18',label: "外国人居留证"},
		{value: '19',label: "警官证 "},
	],
	//证件类型 -列表使用-
	/* cert_typeall: [
		{value: '10',label: "身份证"},
		{value: '11',label: "户口簿"},
		{value: '12',label: "护照 "},
		{value: '13',label: "军官证"},
		{value: '14',label: "士兵证"},
		{value: '15',label: "港澳居民来往内地通行证 "},
		{value: '16',label: "台湾同胞来往内地通行证 "},
		{value: '17',label: "临时身份证 "},
		{value: '18',label: "外国人居留证"},
		{value: '19',label: "警官证 "},
		{value: '1X',label: "其他证件"},
		{value: '20',label: "组织机构代码 "},
		{value: '21',label: "贷款卡编码 "},
		{value: '22',label: "营业执照号码(统一社会信用代码)"},
		{value: '23',label: "民办非企业登记证书 "},
		{value: '24',label: "其他批文或证明"},
		{value: '25',label: "预先核准通知书 "},
		{value: '26',label: "事业单位法人证书 "},
		{value: '27',label: "政府批文"},
		{value: '28',label: "境外企业证书"},
		{value: '29',label: "社会团体法人登记证书"},
		{value: '30',label: "工会法人资格证书"},
	], */
	// 学历
	/* indiv_edt: [{value: "00",label: "博士研究生"},
		{value: "10",label: "硕士研究生"},
		{value: "20",label: "大学本科"},
		{value: "30",label: "大学专科和专科学校"},
		{value: "40",label: "中等专业学校或中等技术学校"},
		{value: "50",label: "技术学校"},
		{value: "60",label: "高中"},
		{value: "70",label: "初中"},
		{value: "80",label: "小学"},
		{value: "90",label: "文盲或半文盲"},
	], */
	// 学位
	/* indiv_dgr: [
		{value: '0',label: '其他'},
		{value: '1',label: '名誉博士'},
		{value: '2',label: '博士'},
		{value: '3',label: '硕士'},
		{value: '4',label: '学士'},
		{value: '9',label: '未知'},
	], */
	// 诚信状况
	/* integstatus: [
		{value: '1',label: '无不良记录'},
		{value: '2',label: '有轻微不良记录'},
		{value: '3',label: '有严重不良记录'},
	], */
	//性别
	indiv_sex: [
		{value: "1",label: "男"},
		{value: "2",label: "女"},
	],
	//婚姻状况
	/* indiv_mar_st:[
		{value:'10', label:'未婚'},
		{value:'20', label:'已婚'},
		{value:'21', label:'初婚'},
		{value:'22', label:'再婚'},
		{value:'23', label:'复婚'},
		{value:'30', label:'丧偶'},
		{value:'40', label:'离婚'},
		{value:'90', label:'未知'},
	], */
	//职业
	/* indiv_occ:[
		{value:'0', label:'国家机关、党群组织负责人'},
		{value:'1', label:'专业技术人员'},
		{value:'3', label:'办事人员和有关人员'},
		{value:'4', label:'商业、服务业人员'},
		{value:'5', label:'农、林、牧、渔、水利业生产人员'},
		{value:'6', label:'生产、运输设备操作人员及有关人员'},
		{value:'7', label:'待业'},
		{value:'8', label:'企业、事业单位负责人'},
		{value:'X', label:'军人'},
		{value:'Y', label:'不便分类的其他从业人员'},
		{value:'Z', label:'未知'},
	], */
	//单位性质
	/* indiv_com_typ:[
		{value:'100', label:'党政机关'},
		{value:'200', label:'事业单位'},
		{value:'300', label:'军队'},
		{value:'400', label:'社会团体'},
		{value:'510', label:'国有企业'},
		{value:'520', label:'集体企业'},
		{value:'530', label:'股份合作企业'},
		{value:'540', label:'联营企业'},
		{value:'550', label:'有限责任公司'},
		{value:'560', label:'股份有限公司'},
		{value:'570', label:'私营企业'},
		{value:'600', label:'外商投资企业(含港、澳、台)'},
		{value:'610', label:'中外合资经营企业(含港、澳、台)'},
		{value:'620', label:'中外合作经营企业(含港、澳、台)'},
		{value:'630', label:'外资企业(含港、澳、台)'},
		{value:'640', label:'外商投资股份有限公司(含港、澳、台)'},
		{value:'700', label:'个体经营'},
		{value:'800', label:'其他'},
		{value:'900', label:'未知'},
	], */
	//职务
	/* indiv_com_job_ttl:[
		{value:'1', label:'高级领导'},
		{value:'2', label:'中级领导'},
		{value:'3', label:'一般员工'},
		{value:'4', label:'其他'},
		{value:'9', label:'未知'},
	], */
	//职称
	/* indiv_crtfctn:[
		{value:'0', label:'无'},
		{value:'1', label:'高级'},
		{value:'2', label:'中级'},
		{value:'3', label:'初级'},
		{value:'9', label:'未知'},
	], */
	//与我行关系
	// cus_bank_rel:[
	// 	{value:'B1', label:'普通客户关系'},
	// 	/* {value:'B3', label:'本行主要股东(持有本行5％（含）以上股份)'},
	// 	{value:'B5', label:'本行股东(持有本行5％以下股份)'}, */
	// 	{value:'B6', label:'本行董事 '},
	// 	{value:'B7', label:'本行普通员工'},
	// 	{value:'B9', label:'本行普通员工亲属'},
	// 	{value:'C3', label:'本行总部高级管理人员'},
	// 	{value:'C4', label:'本行支行高级管理人员'},
	// 	{value:'C6', label:'本行董事近亲属'},
	// 	{value:'C7', label:'本行监事近亲属'},
		// {value:'C8', label:'本行总部高级管理人员近亲属'},
		// {value:'C9', label:'本行支行高级管理人员近亲属'},
		// {value:'D2', label:'本行主要自然人股东近亲属'},
		// {value:'D3', label:'本行关联法人或其他组织的控股自然人股东、董事、关键管理人员'},
		// {value:'D4', label:'本行监事'},
		// {value:'G1', label:'本行分行高级管理人员近亲属'},
		// {value:'G2', label:'本行分行高级管理人员'},
		// {value:'G3', label:'本行有权决定或者参与授信和资产转移的其他人员'},
		// {value:'G4', label:'本行有权决定或者参与授信和资产转移的其他人员近亲属'},
	//],
	// 在我行职务
	/* bank_duty:[
		{value:'1',	label:'理事/董事'},
		{value:'2',	label:'监事'},
		{value:'3',	label:'影响信贷决策的管理人员'},
		{value:'4',	label:'一般员工'},
		{value:'5',	label:'高管'},
	], */
	//上本行黑名单标志
	/* blist_flag:[
		{value:'1',	label:'是'},
		{value:'2',	label:'否'},
	], */
	//渠道来源
	/* is_tax:[
		{value:'1', label:'传统渠道'},
		{value:'2', label:'税e融'},
		{value:'3', label:'税e融转项下'},
		{value:'4', label:'税e融待启用'},
		{value:'5', label:'京小贷'},
	], */
	//信息透明度
	/* transparency:[
		{value:'1', label:'高'},
		{value:'2', label:'中'},
		{value:'3', label:'低'},
	], */
	//组成形式
	/* reg_type:[
		{value:'1', label:'个人经营'},
		{value:'2', label:'家庭经营'},
	], */
	//现住房类别
	/* now_hous_type:[
		{value:'00', label:'平房'},
		{value:'01', label:'楼房'},
		{value:'02', label:'公寓'},
		{value:'04', label:'其他'},
	], */
	//现住房类别
	/* now_property_nature:[
		{value:'00', label:'自购商品房'},
		{value:'01', label:'工作单位所有'},
		{value:'02', label:'房改购房'},
		{value:'04', label:'继承私产'},
		{value:'05', label:'借房'},
		{value:'06', label:'其他'},
	], */
	//政治面貌
	/* indiv_pol_st:[
		{value:'01', label:'中共党员'},
		{value:'02', label:'共青团员'},
		{value:'04', label:'群众'},
	], */
	//
	/* indiv_heal_st:[
		{value:'1', label:'良好'},
		{value:'2', label:'一般'},
		{value:'3', label:'差'},
	], */
	//经营场地所有权
	/* com_opt_owner:[
		{value:'1', label:'自有'},
		{value:'2', label:'租赁'},
		{value:'3', label:'其他'},
	], */
	//企业经营场地所有权
	/* workfieldfee:[
		{value:'1', label:'自有'},
		{value:'2', label:'租赁'},
	], */
	//社会保障情况
	/* indiv_soc_scr:[
		{value:'01', label:'养老保险'},
		{value:'02', label:'失业保险'},
		{value:'04', label:'医疗保险'},
		{value:'05', label:'生育保险'},
		{value:'06', label:'住房公积金'},
		{value:'07', label:'无'},
	], */
	// 居住状况
	/* indiv_rsd_st:[
		{value:'1', label:'自置'},
		{value:'2', label:'按揭'},
		{value:'3', label:'亲属楼宇'},
		{value:'4', label:'集体宿舍'},
		{value:'5', label:'租房'},
		{value:'6', label:'共有住宅'},
		{value:'7', label:'其他'},
		{value:'9', label:'未知'},
	], */
	//企业有无进出口经营权
	/* hasieright:[
		{value:'01', label:'有'},
		{value:'02', label:'无'},
	], */
	
	//企业是否环境达标
	/* enviromenteriendlyflag:[
		{value:'1', label:'是'},
		{value:'2', label:'否'},
		{value:'3', label:'不涉及'},
	], */
	//配偶证件类型
	/* indiv_sps_id_typ:[
		{value:'10', label:'身份证'},
		{value:'12', label:'护照'},
		{value:'13', label:'军官证'},
		{value:'14', label:'士兵证'},
		{value:'15', label:'港澳居民来往内地通行证'},
		{value:'16', label:'台湾同胞来往内地通行证'},
		{value:'18', label:'外国人居留证'},
		{value:'19', label:'警官证'},
	], */
	// 中证码（原贷款卡）状态
	/* loan_card_eff_flg:[
		{value:'01', label:'有效'},
		{value:'02', label:'暂停'},
		{value:'04', label:'吊销'},
		{value:'05', label:'末年检'},
	], */
	//在我行开立账户情况
	/* indiv_hld_acnt:[
		{value:'1',	label:'住房贷款账户'},
		{value:'2',	label:'理财账户'},
		{value:'3',	label:'其他个人贷款账户'},
		{value:'4',	label:'大额储蓄账户(10万元以上)'},
		{value:'5',	label:'个人结算账户'},
	], */
	//持卡情况
	/* hold_card:[
		{value:'1',	label:'无银行卡'},
		{value:'2',	label:'有本行卡'},
		{value:'3',	label:'有他行卡'},
	], */
	//资产类别
	/* indiv_ass_type:[
		{value:'01', label:'土地'},
		{value:'02', label:'房屋'},
		{value:'03', label:'汽车'},
		{value:'04', label:'其他资产'},
		{value:'05', label:'他行存款'},
		{value:'06', label:'他行理财'},
		{value:'07', label:'其他金融产品（非本行存款和理财）'},
	], */
	//抵押状况
	/* com_ass_status:[	
		{value:'01', label:'已抵押'},
		{value:'02', label:'未抵押'},
	], */
	//业务品种细分
	/* biz_type_sub:[
		{value:'022022', label:'其他个人经营贷款'},
		{value:'022242', label:'小微企业汽车贷款'},
	], */
	//民族
	indiv_ntn:[
		{value:"01", label:"汉族"},
		{value:"02", label:"蒙族"},
		{value:"04", label:"藏族"},
		{value:"05", label:"维吾尔族"},
		{value:"06", label:"苗族"},
		{value:"07", label:"彝族"},
		{value:"08", label:"壮族"},
		{value:"10", label:"朝鲜族"},
		{value:"11", label:"满族"},
		{value:"13", label:"瑶族"},
		{value:"14", label:"白族"},
		{value:"15", label:"土家族"},
		{value:"16", label:"哈尼族"},
		{value:"17", label:"哈萨克族"},
		{value:"18", label:"傣族"},
		{value:"19", label:"黎族"},
		{value:"20", label:"僳僳族"},
		{value:"21", label:"佤族"},
		{value:"22", label:"畲族"},
		{value:"23", label:"高山族"},
		{value:"24", label:"拉祜族"},
		{value:"25", label:"水族"},
		{value:"26", label:"东乡族"},
		{value:"27", label:"纳西族"},
		{value:"28", label:"景颇族"},
		{value:"29", label:"柯尔克孜族"},
		{value:"30", label:"土族"},
		{value:"31", label:"达斡尔族"},
		{value:"32", label:"仫佬族"},
		{value:"33", label:"羌族"},
		{value:"34", label:"布朗族"},
		{value:"35", label:"撒拉族"},
		{value:"36", label:"毛难族"},
		{value:"37", label:"仡佬族"},
		{value:"38", label:"锡伯族"},
		{value:"39", label:"阿昌族"},
		{value:"40", label:"普米族"},
		{value:"42", label:"怒族"},
		{value:"43", label:"乌孜别克族"},
		{value:"44", label:"俄罗斯族"},
		{value:"45", label:"鄂温克族"},
		{value:"46", label:"崩龙族"},
		{value:"47", label:"保安族"},
		{value:"48", label:"裕固族"},
		{value:"49", label:"京族"},
		{value:"50", label:"塔塔尔族"},
		{value:"52", label:"鄂伦春族"},
		{value:"53", label:"赫哲族"},
		{value:"54", label:"门巴族"},
		{value:"55", label:"珞巴族"},
		{value:"56", label:"基诺族"},
		{value:"57", label:"回族"},
		{value:"98", label:"外国血统"},
		{value:"99", label:"其他"},
		{value:"9A", label:"外籍人员"},
		{value:"9B", label:"无国籍人员"},
		{value:"9C", label:"香港人"},
		{value:"9D", label:"澳门人"},
		{value:"9E", label:"台湾人"},
		{value:"9F", label:"华侨"},
	],
	//国别
	indiv_country:[
		{value:'CHN',label:'中华人民共和国'},
		{value:'TWN',label:'中国台湾'},
		{value:'ABW',label:'阿鲁巴'},
		{value:'AFG',label:'阿富汗伊斯兰国'},
		{value:'AGO',label:'安哥拉共和国'},
		{value:'ALB',label:'阿尔巴尼亚共和国'},
		{value:'AND',label:'安道尔公国'},
		{value:'ANT',label:'荷属安的列斯'},
		{value:'ARE',label:'阿拉伯联合酋长国'},
		{value:'ARG',label:'阿根廷共和国'},
		{value:'ARM',label:'亚美尼亚共和国'},
		{value:'ASM',label:'美属萨摩亚'},
		{value:'ATA',label:'安圭拉'},
		{value:'ATF',label:'法属南部领土'},
		{value:'ATG',label:'安提瓜和巴布达'},
		{value:'AUS',label:'澳大利亚联邦'},
		{value:'AUT',label:'奥地利共和国'},
		{value:'AZE',label:'阿塞拜疆共和国'},
		{value:'BDI',label:'布隆迪共和国'},
		{value:'BEL',label:'比利时王国'},
		{value:'BEN',label:'贝宁共和国'},
		{value:'BFA',label:'布基纳法索'},
		{value:'BGD',label:'孟加拉人民共和国'},
		{value:'BGR',label:'保加利亚共和国'},
		{value:'BHR',label:'巴林国'},
		{value:'BHS',label:'巴哈马联邦'},
		{value:'BIH',label:'波斯尼亚和黑塞哥维那共和国'},
		{value:'BLR',label:'白俄罗斯共和国'},
		{value:'BLZ',label:'伯利兹'},
		{value:'BMU',label:'百慕大群岛'},
		{value:'BOL',label:'玻利维亚共和国'},
		{value:'BRA',label:'巴西联邦共和国'},
		{value:'BRB',label:'巴巴多斯'},
		{value:'BRN',label:'文莱达鲁萨兰国'},
		{value:'BTN',label:'不丹王国'},
		{value:'BVT',label:'布维岛'},
		{value:'BWA',label:'博茨瓦纳共和国'},
		{value:'CAF',label:'中非共和国'},
		{value:'CAN',label:'加拿大'},
		{value:'CCK',label:'科科斯（基林）群岛'},
		{value:'CHE',label:'瑞士联邦'},
		{value:'CHL',label:'智利共和国'},
		{value:'CIV',label:'科特迪瓦共和国'},
		{value:'CMR',label:'喀麦隆共和国'},
		{value:'COG',label:'刚果共和国'},
		{value:'COK',label:'库克群岛'},
		{value:'COL',label:'哥伦比亚共和国'},
		{value:'COM',label:'科摩罗伊斯兰联邦共和国'},
		{value:'CPV',label:'佛得角共和国'},
		{value:'CSR',label:'圣诞岛'},
		{value:'CUB',label:'古巴共和国'},
		{value:'CYM',label:'开曼群岛'},
		{value:'CYP',label:'塞浦路斯共和国'},
		{value:'CZE',label:'捷克共和国'},
		{value:'DEU',label:'德意志联邦共和国'},
		{value:'DJI',label:'吉布提共和国'},
		{value:'DMA',label:'多米尼克联邦'},
		{value:'DNK',label:'丹麦王国'},
		{value:'DOM',label:'多米尼加共和国'},
		{value:'DZA',label:'阿尔及利亚民主人民共和国'},
		{value:'ECU',label:'厄瓜多尔共和国'},
		{value:'EGY',label:'阿拉伯埃及共和国'},
		{value:'ERI',label:'厄立特里亚国'},
		{value:'ESH',label:'西撒哈拉'},
		{value:'ESP',label:'西班牙'},
		{value:'EST',label:'爱沙尼亚共和国'},
		{value:'ETH',label:'埃塞俄比亚'},
		{value:'FIN',label:'芬兰共和国'},
		{value:'FJI',label:'斐济共和国'},
		{value:'FLK',label:'马尔维纳斯群岛（福克兰群岛）'},
		{value:'FRA',label:'法兰西共和国'},
		{value:'FRO',label:'法罗群岛'},
		{value:'FSM',label:'密克罗尼西亚联邦'},
		{value:'GAB',label:'加蓬共和国'},
		{value:'GBR',label:'大不列颠及北爱尔兰联合王国'},
		{value:'GEO',label:'格鲁吉亚共和国'},
		{value:'GHA',label:'加纳共和国'},
		{value:'GIB',label:'直布罗陀'},
		{value:'GIN',label:'几内亚共和国'},
		{value:'GLP',label:'瓜德罗普'},
		{value:'GMB',label:'冈比亚共和国'},
		{value:'GNB',label:'几内亚比绍共和国'},
		{value:'GNQ',label:'赤道几内亚共和国'},
		{value:'GRC',label:'希腊共和国'},
		{value:'GRD',label:'格林纳达'},
		{value:'GRL',label:'格陵兰'},
		{value:'GTM',label:'危地马拉共和国'},
		{value:'GUF',label:'法属圭亚那'},
		{value:'GUM',label:'关岛'},
		{value:'GUY',label:'圭亚那合作共和国'},
		{value:'HKG',label:'香港'},
		{value:'HMD',label:'赫德岛和麦克唐纳岛'},
		{value:'HND',label:'洪都拉斯共和国'},
		{value:'HRV',label:'克罗地亚共和国'},
		{value:'HTI',label:'海地共和国'},
		{value:'HUN',label:'匈牙利共和国'},
		{value:'IDN',label:'印度尼西亚共和国'},
		{value:'IND',label:'印度共和国'},
		{value:'IOT',label:'英属印度洋领土'},
		{value:'IRL',label:'爱尔兰'},
		{value:'IRN',label:'伊朗伊斯兰共和国'},
		{value:'IRQ',label:'伊拉克共和国'},
		{value:'ISL',label:'冰岛共和国'},
		{value:'ISR',label:'以色列国'},
		{value:'ITA',label:'意大利共和国'},
		{value:'JAM',label:'牙买加'},
		{value:'JOR',label:'约旦哈希姆王国'},
		{value:'JPN',label:'日本国'},
		{value:'KAZ',label:'哈萨克斯坦共和国'},
		{value:'KEN',label:'肯尼亚共和国'},
		{value:'KGZ',label:'吉尔吉斯共和国'},
		{value:'KHM',label:'柬埔寨王国'},
		{value:'KIR',label:'基里巴斯共和国'},
		{value:'KNA',label:'圣革茨和尼维斯联邦'},
		{value:'KOR',label:'大韩民国'},
		{value:'KWT',label:'科威特国'},
		{value:'LAO',label:'老挝人民民主共和国'},
		{value:'LBN',label:'黎巴嫩共和国'},
		{value:'LBR',label:'利比里亚共和国'},
		{value:'LBY',label:'大阿拉伯利比亚人民社会主义民众国'},
		{value:'LCA',label:'圣卢西亚'},
		{value:'LIE',label:'列支敦士登公国'},
		{value:'LKA',label:'斯里兰卡民主社会主义共和国'},
		{value:'LSO',label:'莱索托王国'},
		{value:'LTU',label:'立陶宛共和国'},
		{value:'LUX',label:'卢森堡大公国'},
		{value:'LVA',label:'拉脱维亚共和国'},
		{value:'MAC',label:'澳门'},
		{value:'MAR',label:'摩洛哥王国'},
		{value:'MCO',label:'摩纳哥公国'},
		{value:'MDA',label:'摩尔多瓦共和国'},
		{value:'MDG',label:'马达加斯加共和国'},
		{value:'MDV',label:'马尔代夫共和国'},
		{value:'MEX',label:'墨西哥合众国'},
		{value:'MHL',label:'马绍尔群岛共和国'},
		{value:'MKD',label:'马其顿共和国'},
		{value:'MLI',label:'马里共和国'},
		{value:'MLT',label:'马耳他共和国'},
		{value:'MMR',label:'缅甸联邦'},
		{value:'MNG',label:'蒙古国'},
		{value:'MNP',label:'北马里亚纳自由联邦'},
		{value:'MOZ',label:'莫桑比克共和国'},
		{value:'MSR',label:'蒙特萨拉特'},
		{value:'MTQ',label:'马提尼克'},
		{value:'MUS',label:'毛里求斯共和国'},
		{value:'MWI',label:'马拉维共和国'},
		{value:'MYS',label:'马来西亚'},
		{value:'MYT',label:'马约特'},
		{value:'NAM',label:'纳米比亚共和国'},
		{value:'NCL',label:'新喀里多尼亚'},
		{value:'NER',label:'尼日尔共和国'},
		{value:'NFK',label:'诺福克岛'},
		{value:'NGA',label:'尼日利亚联邦共和国'},
		{value:'NIC',label:'尼加拉瓜共和国'},
		{value:'NIU',label:'纽埃'},
		{value:'NLD',label:'荷兰王国'},
		{value:'NOR',label:'挪威王国'},
		{value:'NPL',label:'尼泊尔王国'},
		{value:'NRU',label:'瑙鲁共和国'},
		{value:'NZL',label:'新西兰'},
		{value:'OMN',label:'阿曼苏丹国'},
		{value:'PAK',label:'巴基斯坦伊斯兰共和国'},
		{value:'PAN',label:'巴拿马共和国'},
		{value:'PCN',label:'皮竺凯恩群岛'},
		{value:'PER',label:'秘鲁共和国'},
		{value:'PHL',label:'菲律宾共和国'},
		{value:'PLW',label:'贝劳共和国'},
		{value:'PNG',label:'巴布亚新几内亚独立国'},
		{value:'POL',label:'波兰共和国'},
		{value:'PRA',label:'巴拉圭共和国'},
		{value:'PRI',label:'波多黎各自由联邦'},
		{value:'PRK',label:'朝鲜民主主义人民共和国'},
		{value:'PRT',label:'葡萄牙共和国'},
		{value:'PST',label:'巴勒斯坦国'},
		{value:'PYF',label:'法属波利尼西亚'},
		{value:'QAT',label:'卡塔尔国'},
		{value:'REU',label:'留尼汪'},
		{value:'ROM',label:'罗马尼亚'},
		{value:'RUS',label:'俄罗斯联邦'},
		{value:'RWA',label:'卢旺达共和国'},
		{value:'SAU',label:'沙特阿拉伯王国'},
		{value:'SDN',label:'苏丹共和国'},
		{value:'SEN',label:'塞内加尔共和国'},
		{value:'SGP',label:'新加坡共和国'},
		{value:'SGS',label:'南乔治亚岛和南桑德韦奇岛'},
		{value:'SHN',label:'圣赫勒拿'},
		{value:'SJM',label:'斯瓦尔巴群岛'},
		{value:'SLB',label:'所罗门群岛'},
		{value:'SLE',label:'塞拉利昂共和国'},
		{value:'SLV',label:'萨尔瓦多共和国'},
		{value:'SMR',label:'圣马力诺共和国'},
		{value:'SOM',label:'索马里共和国'},
		{value:'SPM',label:'圣皮埃尔和密克隆'},
		{value:'STP',label:'圣多美和普林西比民主共和国'},
		{value:'SUR',label:'苏里南共和国'},
		{value:'SVK',label:'斯洛伐克共和国'},
		{value:'SVN',label:'斯洛文尼亚共和国'},
		{value:'SWE',label:'瑞典王国'},
		{value:'SWZ',label:'斯威士兰王国'},
		{value:'SYC',label:'塞舌尔共和国'},
		{value:'SYR',label:'阿拉伯叙利亚共和国'},
		{value:'TCA',label:'特克斯和凯科斯群岛'},
		{value:'TCD',label:'乍得共和国'},
		{value:'TGO',label:'多哥共和国'},
		{value:'THA',label:'泰王国'},
		{value:'TJK',label:'塔吉克斯坦共和国'},
		{value:'TKL',label:'托克劳'},
		{value:'TKM',label:'土库曼斯坦'},
		{value:'TMP',label:'东帝汶'},
		{value:'TON',label:'汤加王国'},
		{value:'TTO',label:'特立尼达和多巴哥共和国'},
		{value:'TUN',label:'突尼斯共和国'},
		{value:'TUR',label:'土耳其共和国'},
		{value:'TUV',label:'图卢瓦'},
		{value:'TZA',label:'坦桑尼亚联合共和国'},
		{value:'UGA',label:'乌干达共和国'},
		{value:'UKR',label:'乌克兰'},
		{value:'URY',label:'乌拉圭东岸共和国'},
		{value:'USA',label:'美利坚合众国'},
		{value:'UZB',label:'乌兹别克斯坦共和国'},
		{value:'VAT',label:'梵蒂冈城国'},
		{value:'VCT',label:'圣文森特和格林纳丁斯'},
		{value:'VEN',label:'委内瑞拉共和国'},
		{value:'VIR',label:'美属维尔京群岛'},
		{value:'VNM',label:'越南社会主义共和国'},
		{value:'VUT',label:'瓦努阿图共和国'},
		{value:'WLF',label:'瓦利斯和富图纳群岛'},
		{value:'WSM',label:'西萨摩亚独立国'},
		{value:'YEM',label:'也门共和国'},
		{value:'YUG',label:'南斯拉夫联盟共和国'},
		{value:'ZAF',label:'南非共和国'},
		{value:'ZAR',label:'扎伊尔共和国'},
		{value:'ZMB',label:'赞比亚共和国'},
		{value:'ZWE',label:'津巴布韦共和国'},
	]
}
